####################################################################
# AUTOSTART
####################################################################

# Authentication
exec-once = /usr/lib/polkit-gnome/polkit-gnome-authentication-agent-1 &

# Desktop components
#exec-once = waybar &
exec-once = awww-daemon &
#exec-once = swaync &

# Clipboard history
exec-once = wl-paste --type text --watch cliphist store
exec-once = wl-paste --type image --watch cliphist store

# File management
exec-once = thunar --daemon &
exec-once = udiskie &

# Network
#exec-once = iwgtk -i &

# Quickshell 
#exec-once = quickshell -p ~/.config/quickshell/mypanel &

##WebbShell
exec-once = webb shell -d
exec-once = webb resizer --daemon &

# Wallpaper (after swww-daemon loads)
#exec-once = sleep 1 && swww img ~/Pictures/wallpapers/wall6.png &

####################################################################
# OPTIONAL
####################################################################

# Clipboard manager
# exec-once = wl-paste --type text --watch cliphist store &
# exec-once = wl-paste --type image --watch cliphist store &

# Idle/lock
# exec-once = hypridle &

# Bluetooth
# exec-once = blueman-applet &

# Network manager
# exec-once = nm-applet --indicator &

# Open apps on startup
# exec-once = [workspace 2 silent] firefox &
# exec-once = [workspace 3 silent] discord &
