####################################################################
#  ██╗  ██╗██╗   ██╗██████╗ ██████╗ ██╗      █████╗ ███╗   ██╗██████╗  
#  ██║  ██║╚██╗ ██╔╝██╔══██╗██╔══██╗██║     ██╔══██╗████╗  ██║██╔══██╗ 
#  ███████║ ╚████╔╝ ██████╔╝██████╔╝██║     ███████║██╔██╗ ██║██║  ██║ 
#  ██╔══██║  ╚██╔╝  ██╔═══╝ ██╔══██╗██║     ██╔══██║██║╚██╗██║██║  ██║ 
#  ██║  ██║   ██║   ██║     ██║  ██║███████╗██║  ██║██║ ╚████║██████╔╝ 
#  ╚═╝  ╚═╝   ╚═╝   ╚═╝     ╚═╝  ╚═╝╚══════╝╚═╝  ╚═╝╚═╝  ╚═══╝╚═════╝  
#                                                                  
#              Hyprland Configuration - Rewritten 2025                 
####################################################################

source = ~/.config/hypr/scheme/current.conf
source = colors.conf 
source = monitors.conf
source = workspaces.conf
source = windowrules.conf
source = programs.conf
source = keybinds.conf
source = autostart.conf
source = env.conf
source = look.conf
source = input.conf


