####################################################################
# PROGRAMS
####################################################################

$terminal = kitty
$fileManager = thunar
$browser = chromium
#$menu = rofi -show drun
$editor = nvim

####################################################################
# ALTERNATIVE PROGRAMS
####################################################################

# Terminals: alacritty, foot, wezterm, warp
# File managers: dolphin, nautilus, nemo, pcmanfm
# Browsers: firefox, brave, microsoft-edge-stable
# Launchers: wofi --show drun, fuzzel, tofi-drun
# Editors: code, gedit, mousepad, helix

####################################################################
# UTILITIES
####################################################################

#$colorPicker = hyprpicker
#$lockScreen = hyprlock
#$logoutMenu = wlogout
#$notifications = swaync
#$statusBar = waybar
#$screenshot = hyprshot

####################################################################
# OPTIONAL
####################################################################

# $videoPlayer = mpv
# $musicPlayer = spotify
# $audioControl = pavucontrol
# $networkManager = iwgtk
# $systemMonitor = btop
