####################################################################
# WINDOW RULES - FIXED
####################################################################

# Webb-Shell
windowrule {
  name = windowrule-1
  float = on
  center = on
  size = 860 600
  match:title = ^(Keybinds)$
}


# Terminal
windowrule = float off, opacity 0.95 0.85, size 1000 600, match:class ^(kitty)$

# File Manager
windowrule = opacity 0.90 0.80, size 1200 700, match:class ^(thunar)$

# System Utilities
windowrule = float off, size 800 600, center on, match:class ^(pavucontrol)$
windowrule = float off, center on, match:class ^(blueman-manager)$
windowrule = float on, center on, match:class ^(nm-connection-editor)$
windowrule = float off, match:class ^(qt5ct)$
windowrule = float off, match:class ^(nwg-look)$

# Color Picker
windowrule = float on, stay_focused on, border_size 0, no_anim on, match:class ^(hyprpicker)$

# Dialogs
windowrule = float on, center on, match:title ^(Open File)
windowrule = float on, center on, match:title ^(Save File)
windowrule = float on, match:title ^(Select a File)
windowrule = float on, match:title ^(Choose)
windowrule = float on, match:title ^(Save As)
windowrule = float on, match:title ^(Confirm)

# Picture-in-Picture
windowrule = float on, pin on, match:title ^(Picture-in-Picture)$

# Suppress maximize
windowrule = suppress_event maximize, match:class .*

