shell /usr/bin/fish

include colors.conf

confirm_os_window_close 0

set TERM "xterm-256colors" 
scrollback_lines 10000

# Font settings
font_family      Fira Code
bold_font        true
italic_font      auto
bold_italic_font auto
font_size        14.0

# Colors
background_opacity 0.90
background_blur 1

# Tab bar
#tab_bar_style powerline
#tab_powerline_style slanted
#tab_bar_min_tabs 1
#tab_title_template "{index}: {title}"

# Keybindings
map ctrl+shift+c copy_to_clipboard
map ctrl+shift+v paste_from_clipboard
