# Base
set -g status-style "bg=#{@thm_bar_bg},fg=#{@thm_fg}"

# Pane borders
set -g pane-border-style "fg=#{@thm_outline}"
set -g pane-active-border-style "fg=#{@thm_primary}"

# Messages
set -g message-style "bg=#{@thm_surface},fg=#{@thm_primary}"

# Modes (copy/resize/etc)
set -g mode-style "bg=#{@thm_primary},fg=#{@thm_bg}"

# ----- STATUS BAR -----

set -g status-left-length 100
set -g status-right-length 100

# Left (session)
set -g status-left "\
#[fg=#{@thm_primary},bg=#{@thm_bar_bg},bold] #S \
#[fg=#{@thm_bar_bg},bg=#{@thm_surface}]"

# Window tabs
set -g window-status-format "\
#[fg=#{@thm_text_variant},bg=#{@thm_surface}] #I:#W "

set -g window-status-current-format "\
#[fg=#{@thm_bg},bg=#{@thm_primary},bold] #I:#W \
#[fg=#{@thm_primary},bg=#{@thm_surface}]"

# Right (time)
set -g status-right "\
#[fg=#{@thm_surface},bg=#{@thm_surface}]\
#[fg=#{@thm_fg},bg=#{@thm_surface}] %H:%M "
