$background = 0d0f0a
$onBackground = e3e7d8
$surface = 0d0f0a
$surfaceDim = 0d0f0a
$surfaceBright = 292e24
$surfaceContainerLowest = 000000
$surfaceContainerLow = 11140e
$surfaceContainer = 171b13
$surfaceContainerHigh = 1d2119
$surfaceContainerHighest = 22271e
$onSurface = e3e7d8
$surfaceVariant = 22271e
$onSurfaceVariant = a8ad9f
$outline = 72776b
$outlineVariant = 444a3e
$inverseSurface = f9faf1
$inverseOnSurface = 54564f
$shadow = 000000
$scrim = 000000
$surfaceTint = b5ce9f
$primary = b5ce9f
$primaryDim = a8c092
$onPrimary = 314622
$primaryContainer = 435833
$onPrimaryContainer = d2ebba
$inversePrimary = 50653e
$primaryFixed = d1ebb9
$primaryFixedDim = c3dcac
$onPrimaryFixed = 314521
$onPrimaryFixedVariant = 4c623b
$secondary = becbae
$secondaryDim = b0bda1
$onSecondary = 38442e
$secondaryContainer = 333f2a
$onSecondaryContainer = b6c4a8
$secondaryFixed = dae7c9
$secondaryFixedDim = ccd9bc
$onSecondaryFixed = 37432e
$onSecondaryFixedVariant = 535f48
$tertiary = fff9e8
$tertiaryDim = efe49f
$onTertiary = 676029
$tertiaryContainer = f8eda7
$onTertiaryContainer = 5f5821
$tertiaryFixed = faefa9
$tertiaryFixedDim = ece19c
$onTertiaryFixed = 4d4712
$onTertiaryFixedVariant = 6b642c
$error = f97758
$errorDim = c44f34
$onError = 450900
$errorContainer = 85230a
$onErrorContainer = ff9b82
$primaryPaletteKeyColor = 677e54
$secondaryPaletteKeyColor = 6f7b62
$tertiaryPaletteKeyColor = 80783e
$neutralPaletteKeyColor = 767871
$neutralVariantPaletteKeyColor = 74796c
$errorPaletteKeyColor = c75236
$primary_paletteKeyColor = 677e54
$secondary_paletteKeyColor = 6f7b62
$tertiary_paletteKeyColor = 80783e
$neutral_paletteKeyColor = 767871
$neutral_variant_paletteKeyColor = 74796c
$term0 = 343433
$term1 = 919700
$term2 = adda70
$term3 = d4f27f
$term4 = 8bb58a
$term5 = c6a844
$term6 = abd592
$term7 = d7dac5
$term8 = a2a493
$term9 = a8b000
$term10 = b8ee72
$term11 = e3ff9f
$term12 = b1c7a8
$term13 = cec06b
$term14 = bbe89b
$term15 = ffffff
$rosewater = f4f2e2
$flamingo = e5e3c4
$pink = ffd79d
$mauve = 5bd0df
$red = c5b542
$maroon = c6c177
$peach = cad48d
$yellow = eaf6c9
$green = beeda0
$teal = bcecb3
$sky = aee9b2
$sapphire = 90d7a0
$blue = 75cf9d
$lavender = 89dcc6
$klink = 3d9764
$klinkSelection = 3d9764
$kvisited = c06b00
$kvisitedSelection = c06b00
$knegative = 8b8d00
$knegativeSelection = 8b8d00
$kneutral = a0b500
$kneutralSelection = a0b500
$kpositive = 6ebc51
$kpositiveSelection = 6ebc51
$text = e3e7d8
$subtext1 = a8ad9f
$subtext0 = 72776b
$overlay2 = 64685d
$overlay1 = 55594f
$overlay0 = 474a41
$surface2 = 393c34
$surface1 = 2b2e27
$surface0 = 1c1e18
$base = 0d0f0a
$mantle = 0d0f0a
$crust = 0c0e09
$success = B5CCBA
$onSuccess = 213528
$successContainer = 374B3E
$onSuccessContainer = D1E9D6
